name: ESlint
on:
  push:
  pull_request:

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: npm install
      run: npm install
    - name: install eslint
      run: npm i eslint
    - name: eslint
      uses: icrawl/action-eslint@v1
      with:
        custom-glob: src
